services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ".:/my-saas"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my-saas-network

  db:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - my-saas-network

volumes:
  postgres_data:

networks:
  my-saas-network:
    driver: bridge
